### ISSUE TITLE
Search query returns no results through API

### ISSUE THREAD

**Issue by gusmclennan** [earowang/romato#2]
Hi there,

Was hoping to utilise this great package to pull some F&B data from Zomato.  I haven't had an issue with any API except the Search function when specifying an entity_id, entity_type, geocodes, radius and cuisines.

Here is my query:
```{r}
# Test search
zmt_data <- zmt$search(entity_id = 171160, entity_type = "subzone", lat = -37.814418, lon = 144.970656, radius = 400, cuisines = 193)
```
This returns: Error: No results were found.

If I run the same query with same parameters through the Zomato API developers site, the query appears to return 5 responses...

![image](https://user-images.githubusercontent.com/15378478/51532856-57973b00-1e95-11e9-8b88-7bebd46bfaf0.png)

Not sure if I am mis-specifying something in the query, or maybe API has been changed recently and requires an update to this package...thanks in advance for any assistance.

**Comment by earowang** [comment]
Thanks. I've updated the code. Should work now.

**Comment by gusmclennan** [comment]
Many thanks @earowang - appears to be working now.  Some of the geocoded doesn't look right, but I suspect that is the data, not the API package ... ; )
